version: '3'

networks:
  web-network:
    driver: bridge

volumes:
  grafana-storage:
  prometheus-storage:

services:
  grafana:
    build:
      context: ./grafana/
    image: grafana/grafana-oss
    environment:
       - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,grafana-polystat-panel
      # - GF_LOG_LEVEL=debug
    ports:
      - "4000:3000"
    networks:
      - web-network
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    build:
      context: ./prometheus/
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/etc:/etc/prometheus
    restart: always
    networks:
      - web-network

  adapter:
    container_name: adapter
    build:
      context: ./adapter/
    volumes:
      - ./adapter/app:/app
    working_dir: /app
    ports:
      - ${LOCAL_PORT}:${LOCAL_PORT}
    environment:
      - SSH_KEY=${SSH_KEY}
      - LOCAL_PORT=${LOCAL_PORT}
      - REMOTE_PORT=${REMOTE_PORT}
      - SSH_USER=${SSH_USER}
      - REMOTE_HOST=${REMOTE_HOST}
    entrypoint: /app/entrypoint.sh
    networks:
      - web-network

